//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitantesBecas.wsSolicitanteBecas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsSolicitanteBecas.SolicitantesBecasSoap")]
    public interface SolicitantesBecasSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/caEscuelas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SolicitantesBecas.wsSolicitanteBecas.StcCaEscuelas caEscuelas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/caUsuarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SolicitantesBecas.wsSolicitanteBecas.StcCaUsuarios caUsuarios();
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StcCaEscuelas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private structBase statusResponseField;
        
        private caEscuelas[] dataField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public structBase statusResponse {
            get {
                return this.statusResponseField;
            }
            set {
                this.statusResponseField = value;
                this.RaisePropertyChanged("statusResponse");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public caEscuelas[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class structBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool statusOperField;
        
        private string messageField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool statusOper {
            get {
                return this.statusOperField;
            }
            set {
                this.statusOperField = value;
                this.RaisePropertyChanged("statusOper");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StcCaUsuarios : object, System.ComponentModel.INotifyPropertyChanged {
        
        private structBase statusResponseField;
        
        private caUsuarios[] dataField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public structBase statusResponse {
            get {
                return this.statusResponseField;
            }
            set {
                this.statusResponseField = value;
                this.RaisePropertyChanged("statusResponse");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public caUsuarios[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class caUsuarios : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string cveUsuarioField;
        
        private string usuarioField;
        
        private System.DateTime fInsField;
        
        private System.Nullable<System.DateTime> fActField;
        
        private maSolicitantes[] maSolicitantesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cveUsuario {
            get {
                return this.cveUsuarioField;
            }
            set {
                this.cveUsuarioField = value;
                this.RaisePropertyChanged("cveUsuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime fIns {
            get {
                return this.fInsField;
            }
            set {
                this.fInsField = value;
                this.RaisePropertyChanged("fIns");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> fAct {
            get {
                return this.fActField;
            }
            set {
                this.fActField = value;
                this.RaisePropertyChanged("fAct");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public maSolicitantes[] maSolicitantes {
            get {
                return this.maSolicitantesField;
            }
            set {
                this.maSolicitantesField = value;
                this.RaisePropertyChanged("maSolicitantes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class maSolicitantes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string curpField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        private string nombresField;
        
        private int edadField;
        
        private int idSexoField;
        
        private string correoField;
        
        private string telCelField;
        
        private string telPartField;
        
        private string domIdMpioField;
        
        private string domIdLocalidadField;
        
        private string domIdColoniaField;
        
        private string domIdCalleField;
        
        private System.Nullable<int> domNumExtField;
        
        private System.Nullable<int> domNumIntField;
        
        private string domLetraField;
        
        private int idEscuelaField;
        
        private string papaPrimerApellidoField;
        
        private string papaSegundoApellidoField;
        
        private string papaNombresField;
        
        private string mamaPrimerApellidoField;
        
        private string mamaSegundoApellidoField;
        
        private string mamaNombresField;
        
        private System.Nullable<int> idDomDescField;
        
        private int idUsuarioField;
        
        private System.DateTime fInsField;
        
        private System.Nullable<System.DateTime> fActField;
        
        private caEdad caEdadField;
        
        private caEscuelas caEscuelasField;
        
        private caSexo caSexoField;
        
        private caUsuarios caUsuariosField;
        
        private tblDomDesc tblDomDescField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string curp {
            get {
                return this.curpField;
            }
            set {
                this.curpField = value;
                this.RaisePropertyChanged("curp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
                this.RaisePropertyChanged("primerApellido");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
                this.RaisePropertyChanged("segundoApellido");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
                this.RaisePropertyChanged("edad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int idSexo {
            get {
                return this.idSexoField;
            }
            set {
                this.idSexoField = value;
                this.RaisePropertyChanged("idSexo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string telCel {
            get {
                return this.telCelField;
            }
            set {
                this.telCelField = value;
                this.RaisePropertyChanged("telCel");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string telPart {
            get {
                return this.telPartField;
            }
            set {
                this.telPartField = value;
                this.RaisePropertyChanged("telPart");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string domIdMpio {
            get {
                return this.domIdMpioField;
            }
            set {
                this.domIdMpioField = value;
                this.RaisePropertyChanged("domIdMpio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string domIdLocalidad {
            get {
                return this.domIdLocalidadField;
            }
            set {
                this.domIdLocalidadField = value;
                this.RaisePropertyChanged("domIdLocalidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string domIdColonia {
            get {
                return this.domIdColoniaField;
            }
            set {
                this.domIdColoniaField = value;
                this.RaisePropertyChanged("domIdColonia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string domIdCalle {
            get {
                return this.domIdCalleField;
            }
            set {
                this.domIdCalleField = value;
                this.RaisePropertyChanged("domIdCalle");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> domNumExt {
            get {
                return this.domNumExtField;
            }
            set {
                this.domNumExtField = value;
                this.RaisePropertyChanged("domNumExt");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<int> domNumInt {
            get {
                return this.domNumIntField;
            }
            set {
                this.domNumIntField = value;
                this.RaisePropertyChanged("domNumInt");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string domLetra {
            get {
                return this.domLetraField;
            }
            set {
                this.domLetraField = value;
                this.RaisePropertyChanged("domLetra");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int idEscuela {
            get {
                return this.idEscuelaField;
            }
            set {
                this.idEscuelaField = value;
                this.RaisePropertyChanged("idEscuela");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string papaPrimerApellido {
            get {
                return this.papaPrimerApellidoField;
            }
            set {
                this.papaPrimerApellidoField = value;
                this.RaisePropertyChanged("papaPrimerApellido");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string papaSegundoApellido {
            get {
                return this.papaSegundoApellidoField;
            }
            set {
                this.papaSegundoApellidoField = value;
                this.RaisePropertyChanged("papaSegundoApellido");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string papaNombres {
            get {
                return this.papaNombresField;
            }
            set {
                this.papaNombresField = value;
                this.RaisePropertyChanged("papaNombres");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string mamaPrimerApellido {
            get {
                return this.mamaPrimerApellidoField;
            }
            set {
                this.mamaPrimerApellidoField = value;
                this.RaisePropertyChanged("mamaPrimerApellido");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string mamaSegundoApellido {
            get {
                return this.mamaSegundoApellidoField;
            }
            set {
                this.mamaSegundoApellidoField = value;
                this.RaisePropertyChanged("mamaSegundoApellido");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string mamaNombres {
            get {
                return this.mamaNombresField;
            }
            set {
                this.mamaNombresField = value;
                this.RaisePropertyChanged("mamaNombres");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<int> idDomDesc {
            get {
                return this.idDomDescField;
            }
            set {
                this.idDomDescField = value;
                this.RaisePropertyChanged("idDomDesc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public System.DateTime fIns {
            get {
                return this.fInsField;
            }
            set {
                this.fInsField = value;
                this.RaisePropertyChanged("fIns");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<System.DateTime> fAct {
            get {
                return this.fActField;
            }
            set {
                this.fActField = value;
                this.RaisePropertyChanged("fAct");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public caEdad caEdad {
            get {
                return this.caEdadField;
            }
            set {
                this.caEdadField = value;
                this.RaisePropertyChanged("caEdad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public caEscuelas caEscuelas {
            get {
                return this.caEscuelasField;
            }
            set {
                this.caEscuelasField = value;
                this.RaisePropertyChanged("caEscuelas");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public caSexo caSexo {
            get {
                return this.caSexoField;
            }
            set {
                this.caSexoField = value;
                this.RaisePropertyChanged("caSexo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public caUsuarios caUsuarios {
            get {
                return this.caUsuariosField;
            }
            set {
                this.caUsuariosField = value;
                this.RaisePropertyChanged("caUsuarios");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public tblDomDesc tblDomDesc {
            get {
                return this.tblDomDescField;
            }
            set {
                this.tblDomDescField = value;
                this.RaisePropertyChanged("tblDomDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class caEdad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int edadField;
        
        private System.DateTime fInsField;
        
        private System.Nullable<System.DateTime> fActField;
        
        private maSolicitantes[] maSolicitantesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
                this.RaisePropertyChanged("edad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime fIns {
            get {
                return this.fInsField;
            }
            set {
                this.fInsField = value;
                this.RaisePropertyChanged("fIns");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> fAct {
            get {
                return this.fActField;
            }
            set {
                this.fActField = value;
                this.RaisePropertyChanged("fAct");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public maSolicitantes[] maSolicitantes {
            get {
                return this.maSolicitantesField;
            }
            set {
                this.maSolicitantesField = value;
                this.RaisePropertyChanged("maSolicitantes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class caEscuelas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string municipioField;
        
        private string institucionField;
        
        private string nivelField;
        
        private string plantelField;
        
        private System.DateTime fInsField;
        
        private System.Nullable<System.DateTime> fActField;
        
        private maSolicitantes[] maSolicitantesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string municipio {
            get {
                return this.municipioField;
            }
            set {
                this.municipioField = value;
                this.RaisePropertyChanged("municipio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string institucion {
            get {
                return this.institucionField;
            }
            set {
                this.institucionField = value;
                this.RaisePropertyChanged("institucion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string nivel {
            get {
                return this.nivelField;
            }
            set {
                this.nivelField = value;
                this.RaisePropertyChanged("nivel");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string plantel {
            get {
                return this.plantelField;
            }
            set {
                this.plantelField = value;
                this.RaisePropertyChanged("plantel");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime fIns {
            get {
                return this.fInsField;
            }
            set {
                this.fInsField = value;
                this.RaisePropertyChanged("fIns");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> fAct {
            get {
                return this.fActField;
            }
            set {
                this.fActField = value;
                this.RaisePropertyChanged("fAct");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public maSolicitantes[] maSolicitantes {
            get {
                return this.maSolicitantesField;
            }
            set {
                this.maSolicitantesField = value;
                this.RaisePropertyChanged("maSolicitantes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class caSexo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string sexoField;
        
        private System.DateTime fInsField;
        
        private System.Nullable<System.DateTime> fActField;
        
        private maSolicitantes[] maSolicitantesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime fIns {
            get {
                return this.fInsField;
            }
            set {
                this.fInsField = value;
                this.RaisePropertyChanged("fIns");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> fAct {
            get {
                return this.fActField;
            }
            set {
                this.fActField = value;
                this.RaisePropertyChanged("fAct");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public maSolicitantes[] maSolicitantes {
            get {
                return this.maSolicitantesField;
            }
            set {
                this.maSolicitantesField = value;
                this.RaisePropertyChanged("maSolicitantes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tblDomDesc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string municipioField;
        
        private string localidadField;
        
        private string coloniaField;
        
        private string calleField;
        
        private System.DateTime fInsField;
        
        private System.Nullable<System.DateTime> factField;
        
        private maSolicitantes[] maSolicitantesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string municipio {
            get {
                return this.municipioField;
            }
            set {
                this.municipioField = value;
                this.RaisePropertyChanged("municipio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
                this.RaisePropertyChanged("localidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string colonia {
            get {
                return this.coloniaField;
            }
            set {
                this.coloniaField = value;
                this.RaisePropertyChanged("colonia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string calle {
            get {
                return this.calleField;
            }
            set {
                this.calleField = value;
                this.RaisePropertyChanged("calle");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime fIns {
            get {
                return this.fInsField;
            }
            set {
                this.fInsField = value;
                this.RaisePropertyChanged("fIns");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> fact {
            get {
                return this.factField;
            }
            set {
                this.factField = value;
                this.RaisePropertyChanged("fact");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public maSolicitantes[] maSolicitantes {
            get {
                return this.maSolicitantesField;
            }
            set {
                this.maSolicitantesField = value;
                this.RaisePropertyChanged("maSolicitantes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SolicitantesBecasSoapChannel : SolicitantesBecas.wsSolicitanteBecas.SolicitantesBecasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SolicitantesBecasSoapClient : System.ServiceModel.ClientBase<SolicitantesBecas.wsSolicitanteBecas.SolicitantesBecasSoap>, SolicitantesBecas.wsSolicitanteBecas.SolicitantesBecasSoap {
        
        public SolicitantesBecasSoapClient() {
        }
        
        public SolicitantesBecasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SolicitantesBecasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitantesBecasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitantesBecasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolicitantesBecas.wsSolicitanteBecas.StcCaEscuelas caEscuelas() {
            return base.Channel.caEscuelas();
        }
        
        public SolicitantesBecas.wsSolicitanteBecas.StcCaUsuarios caUsuarios() {
            return base.Channel.caUsuarios();
        }
    }
}
