//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
// 
#pragma warning disable 1591

namespace SolicitantesBecas.wsSolicitanteBecas {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SolicitantesBecasSoap", Namespace="http://tempuri.org/")]
    public partial class SolicitantesBecas : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback caEscuelasOperationCompleted;
        
        private System.Threading.SendOrPostCallback caUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback verificaCURPInsertadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback instertaSolicitudOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SolicitantesBecas() {
            this.Url = global::SolicitantesBecas.Properties.Settings.Default.wsSolicitantesBecas;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event caEscuelasCompletedEventHandler caEscuelasCompleted;
        
        /// <remarks/>
        public event caUsuariosCompletedEventHandler caUsuariosCompleted;
        
        /// <remarks/>
        public event verificaCURPInsertadoCompletedEventHandler verificaCURPInsertadoCompleted;
        
        /// <remarks/>
        public event instertaSolicitudCompletedEventHandler instertaSolicitudCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/caEscuelas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StcCaEscuelas caEscuelas() {
            object[] results = this.Invoke("caEscuelas", new object[0]);
            return ((StcCaEscuelas)(results[0]));
        }
        
        /// <remarks/>
        public void caEscuelasAsync() {
            this.caEscuelasAsync(null);
        }
        
        /// <remarks/>
        public void caEscuelasAsync(object userState) {
            if ((this.caEscuelasOperationCompleted == null)) {
                this.caEscuelasOperationCompleted = new System.Threading.SendOrPostCallback(this.OncaEscuelasOperationCompleted);
            }
            this.InvokeAsync("caEscuelas", new object[0], this.caEscuelasOperationCompleted, userState);
        }
        
        private void OncaEscuelasOperationCompleted(object arg) {
            if ((this.caEscuelasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.caEscuelasCompleted(this, new caEscuelasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/caUsuarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StcCaUsuarios caUsuarios() {
            object[] results = this.Invoke("caUsuarios", new object[0]);
            return ((StcCaUsuarios)(results[0]));
        }
        
        /// <remarks/>
        public void caUsuariosAsync() {
            this.caUsuariosAsync(null);
        }
        
        /// <remarks/>
        public void caUsuariosAsync(object userState) {
            if ((this.caUsuariosOperationCompleted == null)) {
                this.caUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OncaUsuariosOperationCompleted);
            }
            this.InvokeAsync("caUsuarios", new object[0], this.caUsuariosOperationCompleted, userState);
        }
        
        private void OncaUsuariosOperationCompleted(object arg) {
            if ((this.caUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.caUsuariosCompleted(this, new caUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verificaCURPInsertado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StcisInserted verificaCURPInsertado(int idUsuario, string CURP) {
            object[] results = this.Invoke("verificaCURPInsertado", new object[] {
                        idUsuario,
                        CURP});
            return ((StcisInserted)(results[0]));
        }
        
        /// <remarks/>
        public void verificaCURPInsertadoAsync(int idUsuario, string CURP) {
            this.verificaCURPInsertadoAsync(idUsuario, CURP, null);
        }
        
        /// <remarks/>
        public void verificaCURPInsertadoAsync(int idUsuario, string CURP, object userState) {
            if ((this.verificaCURPInsertadoOperationCompleted == null)) {
                this.verificaCURPInsertadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverificaCURPInsertadoOperationCompleted);
            }
            this.InvokeAsync("verificaCURPInsertado", new object[] {
                        idUsuario,
                        CURP}, this.verificaCURPInsertadoOperationCompleted, userState);
        }
        
        private void OnverificaCURPInsertadoOperationCompleted(object arg) {
            if ((this.verificaCURPInsertadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verificaCURPInsertadoCompleted(this, new verificaCURPInsertadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/instertaSolicitud", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StcInsertaSolicitud instertaSolicitud(int idUsuario, string xmlData) {
            object[] results = this.Invoke("instertaSolicitud", new object[] {
                        idUsuario,
                        xmlData});
            return ((StcInsertaSolicitud)(results[0]));
        }
        
        /// <remarks/>
        public void instertaSolicitudAsync(int idUsuario, string xmlData) {
            this.instertaSolicitudAsync(idUsuario, xmlData, null);
        }
        
        /// <remarks/>
        public void instertaSolicitudAsync(int idUsuario, string xmlData, object userState) {
            if ((this.instertaSolicitudOperationCompleted == null)) {
                this.instertaSolicitudOperationCompleted = new System.Threading.SendOrPostCallback(this.OninstertaSolicitudOperationCompleted);
            }
            this.InvokeAsync("instertaSolicitud", new object[] {
                        idUsuario,
                        xmlData}, this.instertaSolicitudOperationCompleted, userState);
        }
        
        private void OninstertaSolicitudOperationCompleted(object arg) {
            if ((this.instertaSolicitudCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.instertaSolicitudCompleted(this, new instertaSolicitudCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StcCaEscuelas {
        
        private structBase statusResponseField;
        
        private caEscuelas[] dataField;
        
        /// <comentarios/>
        public structBase statusResponse {
            get {
                return this.statusResponseField;
            }
            set {
                this.statusResponseField = value;
            }
        }
        
        /// <comentarios/>
        public caEscuelas[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class structBase {
        
        private bool statusOperField;
        
        private string messageField;
        
        /// <comentarios/>
        public bool statusOper {
            get {
                return this.statusOperField;
            }
            set {
                this.statusOperField = value;
            }
        }
        
        /// <comentarios/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StcInsertaSolicitud {
        
        private structBase statusResponseField;
        
        /// <comentarios/>
        public structBase statusResponse {
            get {
                return this.statusResponseField;
            }
            set {
                this.statusResponseField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Inserted {
        
        private bool insertedField;
        
        private string messageField;
        
        private string cURPField;
        
        private int idUsuarioField;
        
        /// <comentarios/>
        public bool inserted {
            get {
                return this.insertedField;
            }
            set {
                this.insertedField = value;
            }
        }
        
        /// <comentarios/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <comentarios/>
        public string CURP {
            get {
                return this.cURPField;
            }
            set {
                this.cURPField = value;
            }
        }
        
        /// <comentarios/>
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StcisInserted {
        
        private structBase statusResponseField;
        
        private Inserted dataField;
        
        /// <comentarios/>
        public structBase statusResponse {
            get {
                return this.statusResponseField;
            }
            set {
                this.statusResponseField = value;
            }
        }
        
        /// <comentarios/>
        public Inserted data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StcCaUsuarios {
        
        private structBase statusResponseField;
        
        private caUsuarios[] dataField;
        
        /// <comentarios/>
        public structBase statusResponse {
            get {
                return this.statusResponseField;
            }
            set {
                this.statusResponseField = value;
            }
        }
        
        /// <comentarios/>
        public caUsuarios[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class caUsuarios {
        
        private int idField;
        
        private string cveUsuarioField;
        
        private string usuarioField;
        
        private System.DateTime fInsField;
        
        private System.Nullable<System.DateTime> fActField;
        
        private maSolicitantes[] maSolicitantesField;
        
        /// <comentarios/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string cveUsuario {
            get {
                return this.cveUsuarioField;
            }
            set {
                this.cveUsuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime fIns {
            get {
                return this.fInsField;
            }
            set {
                this.fInsField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fAct {
            get {
                return this.fActField;
            }
            set {
                this.fActField = value;
            }
        }
        
        /// <comentarios/>
        public maSolicitantes[] maSolicitantes {
            get {
                return this.maSolicitantesField;
            }
            set {
                this.maSolicitantesField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class maSolicitantes {
        
        private int idField;
        
        private string curpField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        private string nombresField;
        
        private int edadField;
        
        private string sexoField;
        
        private string correoField;
        
        private string telCelField;
        
        private string telPartField;
        
        private string domIdMpioField;
        
        private string domIdLocalidadField;
        
        private string domIdColoniaField;
        
        private string domIdCalleField;
        
        private System.Nullable<int> domNumExtField;
        
        private System.Nullable<int> domNumIntField;
        
        private string domLetraField;
        
        private int idEscuelaField;
        
        private string papaPrimerApellidoField;
        
        private string papaSegundoApellidoField;
        
        private string papaNombresField;
        
        private string mamaPrimerApellidoField;
        
        private string mamaSegundoApellidoField;
        
        private string mamaNombresField;
        
        private string domDescField;
        
        private int idUsuarioField;
        
        private System.DateTime fInsField;
        
        private System.Nullable<System.DateTime> fActField;
        
        private caEscuelas caEscuelasField;
        
        private caUsuarios caUsuariosField;
        
        /// <comentarios/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string curp {
            get {
                return this.curpField;
            }
            set {
                this.curpField = value;
            }
        }
        
        /// <comentarios/>
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
            }
        }
        
        /// <comentarios/>
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
            }
        }
        
        /// <comentarios/>
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
            }
        }
        
        /// <comentarios/>
        public int edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
            }
        }
        
        /// <comentarios/>
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <comentarios/>
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
        
        /// <comentarios/>
        public string telCel {
            get {
                return this.telCelField;
            }
            set {
                this.telCelField = value;
            }
        }
        
        /// <comentarios/>
        public string telPart {
            get {
                return this.telPartField;
            }
            set {
                this.telPartField = value;
            }
        }
        
        /// <comentarios/>
        public string domIdMpio {
            get {
                return this.domIdMpioField;
            }
            set {
                this.domIdMpioField = value;
            }
        }
        
        /// <comentarios/>
        public string domIdLocalidad {
            get {
                return this.domIdLocalidadField;
            }
            set {
                this.domIdLocalidadField = value;
            }
        }
        
        /// <comentarios/>
        public string domIdColonia {
            get {
                return this.domIdColoniaField;
            }
            set {
                this.domIdColoniaField = value;
            }
        }
        
        /// <comentarios/>
        public string domIdCalle {
            get {
                return this.domIdCalleField;
            }
            set {
                this.domIdCalleField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> domNumExt {
            get {
                return this.domNumExtField;
            }
            set {
                this.domNumExtField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> domNumInt {
            get {
                return this.domNumIntField;
            }
            set {
                this.domNumIntField = value;
            }
        }
        
        /// <comentarios/>
        public string domLetra {
            get {
                return this.domLetraField;
            }
            set {
                this.domLetraField = value;
            }
        }
        
        /// <comentarios/>
        public int idEscuela {
            get {
                return this.idEscuelaField;
            }
            set {
                this.idEscuelaField = value;
            }
        }
        
        /// <comentarios/>
        public string papaPrimerApellido {
            get {
                return this.papaPrimerApellidoField;
            }
            set {
                this.papaPrimerApellidoField = value;
            }
        }
        
        /// <comentarios/>
        public string papaSegundoApellido {
            get {
                return this.papaSegundoApellidoField;
            }
            set {
                this.papaSegundoApellidoField = value;
            }
        }
        
        /// <comentarios/>
        public string papaNombres {
            get {
                return this.papaNombresField;
            }
            set {
                this.papaNombresField = value;
            }
        }
        
        /// <comentarios/>
        public string mamaPrimerApellido {
            get {
                return this.mamaPrimerApellidoField;
            }
            set {
                this.mamaPrimerApellidoField = value;
            }
        }
        
        /// <comentarios/>
        public string mamaSegundoApellido {
            get {
                return this.mamaSegundoApellidoField;
            }
            set {
                this.mamaSegundoApellidoField = value;
            }
        }
        
        /// <comentarios/>
        public string mamaNombres {
            get {
                return this.mamaNombresField;
            }
            set {
                this.mamaNombresField = value;
            }
        }
        
        /// <comentarios/>
        public string domDesc {
            get {
                return this.domDescField;
            }
            set {
                this.domDescField = value;
            }
        }
        
        /// <comentarios/>
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime fIns {
            get {
                return this.fInsField;
            }
            set {
                this.fInsField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fAct {
            get {
                return this.fActField;
            }
            set {
                this.fActField = value;
            }
        }
        
        /// <comentarios/>
        public caEscuelas caEscuelas {
            get {
                return this.caEscuelasField;
            }
            set {
                this.caEscuelasField = value;
            }
        }
        
        /// <comentarios/>
        public caUsuarios caUsuarios {
            get {
                return this.caUsuariosField;
            }
            set {
                this.caUsuariosField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class caEscuelas {
        
        private int idField;
        
        private string municipioField;
        
        private string institucionField;
        
        private string nivelField;
        
        private string plantelField;
        
        private System.DateTime fInsField;
        
        private System.Nullable<System.DateTime> fActField;
        
        private maSolicitantes[] maSolicitantesField;
        
        /// <comentarios/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string municipio {
            get {
                return this.municipioField;
            }
            set {
                this.municipioField = value;
            }
        }
        
        /// <comentarios/>
        public string institucion {
            get {
                return this.institucionField;
            }
            set {
                this.institucionField = value;
            }
        }
        
        /// <comentarios/>
        public string nivel {
            get {
                return this.nivelField;
            }
            set {
                this.nivelField = value;
            }
        }
        
        /// <comentarios/>
        public string plantel {
            get {
                return this.plantelField;
            }
            set {
                this.plantelField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime fIns {
            get {
                return this.fInsField;
            }
            set {
                this.fInsField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fAct {
            get {
                return this.fActField;
            }
            set {
                this.fActField = value;
            }
        }
        
        /// <comentarios/>
        public maSolicitantes[] maSolicitantes {
            get {
                return this.maSolicitantesField;
            }
            set {
                this.maSolicitantesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void caEscuelasCompletedEventHandler(object sender, caEscuelasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class caEscuelasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal caEscuelasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StcCaEscuelas Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StcCaEscuelas)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void caUsuariosCompletedEventHandler(object sender, caUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class caUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal caUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StcCaUsuarios Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StcCaUsuarios)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void verificaCURPInsertadoCompletedEventHandler(object sender, verificaCURPInsertadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verificaCURPInsertadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verificaCURPInsertadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StcisInserted Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StcisInserted)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void instertaSolicitudCompletedEventHandler(object sender, instertaSolicitudCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class instertaSolicitudCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal instertaSolicitudCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StcInsertaSolicitud Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StcInsertaSolicitud)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591