#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsSolicitantesBecas.Modelos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BdCapturaBECAS")]
	public partial class BdCapturaBECASDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertcaCalles(caCalles instance);
    partial void UpdatecaCalles(caCalles instance);
    partial void DeletecaCalles(caCalles instance);
    partial void InsertmaSolicitantes(maSolicitantes instance);
    partial void UpdatemaSolicitantes(maSolicitantes instance);
    partial void DeletemaSolicitantes(maSolicitantes instance);
    partial void InsertcaColonias(caColonias instance);
    partial void UpdatecaColonias(caColonias instance);
    partial void DeletecaColonias(caColonias instance);
    partial void InsertcaEscuelas(caEscuelas instance);
    partial void UpdatecaEscuelas(caEscuelas instance);
    partial void DeletecaEscuelas(caEscuelas instance);
    partial void InsertcaLocalidades(caLocalidades instance);
    partial void UpdatecaLocalidades(caLocalidades instance);
    partial void DeletecaLocalidades(caLocalidades instance);
    partial void InsertcaMunicipios(caMunicipios instance);
    partial void UpdatecaMunicipios(caMunicipios instance);
    partial void DeletecaMunicipios(caMunicipios instance);
    partial void InsertcaUsuarios(caUsuarios instance);
    partial void UpdatecaUsuarios(caUsuarios instance);
    partial void DeletecaUsuarios(caUsuarios instance);
    #endregion
		
		public BdCapturaBECASDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BdCapturaBECASConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BdCapturaBECASDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BdCapturaBECASDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BdCapturaBECASDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BdCapturaBECASDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<caCalles> caCalles
		{
			get
			{
				return this.GetTable<caCalles>();
			}
		}
		
		public System.Data.Linq.Table<maSolicitantes> maSolicitantes
		{
			get
			{
				return this.GetTable<maSolicitantes>();
			}
		}
		
		public System.Data.Linq.Table<caColonias> caColonias
		{
			get
			{
				return this.GetTable<caColonias>();
			}
		}
		
		public System.Data.Linq.Table<caEscuelas> caEscuelas
		{
			get
			{
				return this.GetTable<caEscuelas>();
			}
		}
		
		public System.Data.Linq.Table<caLocalidades> caLocalidades
		{
			get
			{
				return this.GetTable<caLocalidades>();
			}
		}
		
		public System.Data.Linq.Table<caMunicipios> caMunicipios
		{
			get
			{
				return this.GetTable<caMunicipios>();
			}
		}
		
		public System.Data.Linq.Table<caUsuarios> caUsuarios
		{
			get
			{
				return this.GetTable<caUsuarios>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.paListaRegistrosExtendida")]
		public ISingleResult<paListaRegistrosExtendidaResult> paListaRegistrosExtendida([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((ISingleResult<paListaRegistrosExtendidaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.paListaRegistrosReducida")]
		public ISingleResult<paListaRegistrosReducidaResult> paListaRegistrosReducida([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((ISingleResult<paListaRegistrosReducidaResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.caCalles")]
	public partial class caCalles : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private string _calles;
		
		private System.DateTime _fIns;
		
		private System.Nullable<System.DateTime> _fAct;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OncallesChanging(string value);
    partial void OncallesChanged();
    partial void OnfInsChanging(System.DateTime value);
    partial void OnfInsChanged();
    partial void OnfActChanging(System.Nullable<System.DateTime> value);
    partial void OnfActChanged();
    #endregion
		
		public caCalles()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calles", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string calles
		{
			get
			{
				return this._calles;
			}
			set
			{
				if ((this._calles != value))
				{
					this.OncallesChanging(value);
					this.SendPropertyChanging();
					this._calles = value;
					this.SendPropertyChanged("calles");
					this.OncallesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fIns", DbType="DateTime NOT NULL", IsDbGenerated=true)]
		public System.DateTime fIns
		{
			get
			{
				return this._fIns;
			}
			set
			{
				if ((this._fIns != value))
				{
					this.OnfInsChanging(value);
					this.SendPropertyChanging();
					this._fIns = value;
					this.SendPropertyChanged("fIns");
					this.OnfInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAct", DbType="DateTime")]
		public System.Nullable<System.DateTime> fAct
		{
			get
			{
				return this._fAct;
			}
			set
			{
				if ((this._fAct != value))
				{
					this.OnfActChanging(value);
					this.SendPropertyChanging();
					this._fAct = value;
					this.SendPropertyChanged("fAct");
					this.OnfActChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.maSolicitantes")]
	public partial class maSolicitantes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _curp;
		
		private int _idUsuario;
		
		private string _primerApellido;
		
		private string _segundoApellido;
		
		private string _nombres;
		
		private int _edad;
		
		private string _sexo;
		
		private string _correo;
		
		private string _telCel;
		
		private string _telPart;
		
		private System.Nullable<System.Guid> _domIdMpio;
		
		private System.Nullable<System.Guid> _domIdLocalidad;
		
		private System.Nullable<System.Guid> _domIdColonia;
		
		private System.Nullable<System.Guid> _domIdCalle;
		
		private System.Nullable<int> _domNumExt;
		
		private System.Nullable<int> _domNumInt;
		
		private string _domLetra;
		
		private int _idEscuela;
		
		private string _papaPrimerApellido;
		
		private string _papaSegundoApellido;
		
		private string _papaNombres;
		
		private string _mamaPrimerApellido;
		
		private string _mamaSegundoApellido;
		
		private string _mamaNombres;
		
		private string _domDesc;
		
		private System.DateTime _fIns;
		
		private System.Nullable<System.DateTime> _fAct;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncurpChanging(string value);
    partial void OncurpChanged();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    partial void OnprimerApellidoChanging(string value);
    partial void OnprimerApellidoChanged();
    partial void OnsegundoApellidoChanging(string value);
    partial void OnsegundoApellidoChanged();
    partial void OnnombresChanging(string value);
    partial void OnnombresChanged();
    partial void OnedadChanging(int value);
    partial void OnedadChanged();
    partial void OnsexoChanging(string value);
    partial void OnsexoChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OntelCelChanging(string value);
    partial void OntelCelChanged();
    partial void OntelPartChanging(string value);
    partial void OntelPartChanged();
    partial void OndomIdMpioChanging(System.Nullable<System.Guid> value);
    partial void OndomIdMpioChanged();
    partial void OndomIdLocalidadChanging(System.Nullable<System.Guid> value);
    partial void OndomIdLocalidadChanged();
    partial void OndomIdColoniaChanging(System.Nullable<System.Guid> value);
    partial void OndomIdColoniaChanged();
    partial void OndomIdCalleChanging(System.Nullable<System.Guid> value);
    partial void OndomIdCalleChanged();
    partial void OndomNumExtChanging(System.Nullable<int> value);
    partial void OndomNumExtChanged();
    partial void OndomNumIntChanging(System.Nullable<int> value);
    partial void OndomNumIntChanged();
    partial void OndomLetraChanging(string value);
    partial void OndomLetraChanged();
    partial void OnidEscuelaChanging(int value);
    partial void OnidEscuelaChanged();
    partial void OnpapaPrimerApellidoChanging(string value);
    partial void OnpapaPrimerApellidoChanged();
    partial void OnpapaSegundoApellidoChanging(string value);
    partial void OnpapaSegundoApellidoChanged();
    partial void OnpapaNombresChanging(string value);
    partial void OnpapaNombresChanged();
    partial void OnmamaPrimerApellidoChanging(string value);
    partial void OnmamaPrimerApellidoChanged();
    partial void OnmamaSegundoApellidoChanging(string value);
    partial void OnmamaSegundoApellidoChanged();
    partial void OnmamaNombresChanging(string value);
    partial void OnmamaNombresChanged();
    partial void OndomDescChanging(string value);
    partial void OndomDescChanged();
    partial void OnfInsChanging(System.DateTime value);
    partial void OnfInsChanged();
    partial void OnfActChanging(System.Nullable<System.DateTime> value);
    partial void OnfActChanged();
    #endregion
		
		public maSolicitantes()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curp", DbType="VarChar(18) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string curp
		{
			get
			{
				return this._curp;
			}
			set
			{
				if ((this._curp != value))
				{
					this.OncurpChanging(value);
					this.SendPropertyChanging();
					this._curp = value;
					this.SendPropertyChanged("curp");
					this.OncurpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primerApellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string primerApellido
		{
			get
			{
				return this._primerApellido;
			}
			set
			{
				if ((this._primerApellido != value))
				{
					this.OnprimerApellidoChanging(value);
					this.SendPropertyChanging();
					this._primerApellido = value;
					this.SendPropertyChanged("primerApellido");
					this.OnprimerApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segundoApellido", DbType="VarChar(50)")]
		public string segundoApellido
		{
			get
			{
				return this._segundoApellido;
			}
			set
			{
				if ((this._segundoApellido != value))
				{
					this.OnsegundoApellidoChanging(value);
					this.SendPropertyChanging();
					this._segundoApellido = value;
					this.SendPropertyChanged("segundoApellido");
					this.OnsegundoApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this.OnnombresChanging(value);
					this.SendPropertyChanging();
					this._nombres = value;
					this.SendPropertyChanged("nombres");
					this.OnnombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edad", DbType="Int NOT NULL")]
		public int edad
		{
			get
			{
				return this._edad;
			}
			set
			{
				if ((this._edad != value))
				{
					this.OnedadChanging(value);
					this.SendPropertyChanging();
					this._edad = value;
					this.SendPropertyChanged("edad");
					this.OnedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(50)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telCel", DbType="VarChar(50)")]
		public string telCel
		{
			get
			{
				return this._telCel;
			}
			set
			{
				if ((this._telCel != value))
				{
					this.OntelCelChanging(value);
					this.SendPropertyChanging();
					this._telCel = value;
					this.SendPropertyChanged("telCel");
					this.OntelCelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telPart", DbType="VarChar(50)")]
		public string telPart
		{
			get
			{
				return this._telPart;
			}
			set
			{
				if ((this._telPart != value))
				{
					this.OntelPartChanging(value);
					this.SendPropertyChanging();
					this._telPart = value;
					this.SendPropertyChanged("telPart");
					this.OntelPartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domIdMpio", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> domIdMpio
		{
			get
			{
				return this._domIdMpio;
			}
			set
			{
				if ((this._domIdMpio != value))
				{
					this.OndomIdMpioChanging(value);
					this.SendPropertyChanging();
					this._domIdMpio = value;
					this.SendPropertyChanged("domIdMpio");
					this.OndomIdMpioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domIdLocalidad", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> domIdLocalidad
		{
			get
			{
				return this._domIdLocalidad;
			}
			set
			{
				if ((this._domIdLocalidad != value))
				{
					this.OndomIdLocalidadChanging(value);
					this.SendPropertyChanging();
					this._domIdLocalidad = value;
					this.SendPropertyChanged("domIdLocalidad");
					this.OndomIdLocalidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domIdColonia", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> domIdColonia
		{
			get
			{
				return this._domIdColonia;
			}
			set
			{
				if ((this._domIdColonia != value))
				{
					this.OndomIdColoniaChanging(value);
					this.SendPropertyChanging();
					this._domIdColonia = value;
					this.SendPropertyChanged("domIdColonia");
					this.OndomIdColoniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domIdCalle", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> domIdCalle
		{
			get
			{
				return this._domIdCalle;
			}
			set
			{
				if ((this._domIdCalle != value))
				{
					this.OndomIdCalleChanging(value);
					this.SendPropertyChanging();
					this._domIdCalle = value;
					this.SendPropertyChanged("domIdCalle");
					this.OndomIdCalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domNumExt", DbType="Int")]
		public System.Nullable<int> domNumExt
		{
			get
			{
				return this._domNumExt;
			}
			set
			{
				if ((this._domNumExt != value))
				{
					this.OndomNumExtChanging(value);
					this.SendPropertyChanging();
					this._domNumExt = value;
					this.SendPropertyChanged("domNumExt");
					this.OndomNumExtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domNumInt", DbType="Int")]
		public System.Nullable<int> domNumInt
		{
			get
			{
				return this._domNumInt;
			}
			set
			{
				if ((this._domNumInt != value))
				{
					this.OndomNumIntChanging(value);
					this.SendPropertyChanging();
					this._domNumInt = value;
					this.SendPropertyChanged("domNumInt");
					this.OndomNumIntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domLetra", DbType="NVarChar(2)")]
		public string domLetra
		{
			get
			{
				return this._domLetra;
			}
			set
			{
				if ((this._domLetra != value))
				{
					this.OndomLetraChanging(value);
					this.SendPropertyChanging();
					this._domLetra = value;
					this.SendPropertyChanged("domLetra");
					this.OndomLetraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEscuela", DbType="Int NOT NULL")]
		public int idEscuela
		{
			get
			{
				return this._idEscuela;
			}
			set
			{
				if ((this._idEscuela != value))
				{
					this.OnidEscuelaChanging(value);
					this.SendPropertyChanging();
					this._idEscuela = value;
					this.SendPropertyChanged("idEscuela");
					this.OnidEscuelaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_papaPrimerApellido", DbType="VarChar(50)")]
		public string papaPrimerApellido
		{
			get
			{
				return this._papaPrimerApellido;
			}
			set
			{
				if ((this._papaPrimerApellido != value))
				{
					this.OnpapaPrimerApellidoChanging(value);
					this.SendPropertyChanging();
					this._papaPrimerApellido = value;
					this.SendPropertyChanged("papaPrimerApellido");
					this.OnpapaPrimerApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_papaSegundoApellido", DbType="VarChar(50)")]
		public string papaSegundoApellido
		{
			get
			{
				return this._papaSegundoApellido;
			}
			set
			{
				if ((this._papaSegundoApellido != value))
				{
					this.OnpapaSegundoApellidoChanging(value);
					this.SendPropertyChanging();
					this._papaSegundoApellido = value;
					this.SendPropertyChanged("papaSegundoApellido");
					this.OnpapaSegundoApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_papaNombres", DbType="VarChar(50)")]
		public string papaNombres
		{
			get
			{
				return this._papaNombres;
			}
			set
			{
				if ((this._papaNombres != value))
				{
					this.OnpapaNombresChanging(value);
					this.SendPropertyChanging();
					this._papaNombres = value;
					this.SendPropertyChanged("papaNombres");
					this.OnpapaNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mamaPrimerApellido", DbType="VarChar(50)")]
		public string mamaPrimerApellido
		{
			get
			{
				return this._mamaPrimerApellido;
			}
			set
			{
				if ((this._mamaPrimerApellido != value))
				{
					this.OnmamaPrimerApellidoChanging(value);
					this.SendPropertyChanging();
					this._mamaPrimerApellido = value;
					this.SendPropertyChanged("mamaPrimerApellido");
					this.OnmamaPrimerApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mamaSegundoApellido", DbType="VarChar(50)")]
		public string mamaSegundoApellido
		{
			get
			{
				return this._mamaSegundoApellido;
			}
			set
			{
				if ((this._mamaSegundoApellido != value))
				{
					this.OnmamaSegundoApellidoChanging(value);
					this.SendPropertyChanging();
					this._mamaSegundoApellido = value;
					this.SendPropertyChanged("mamaSegundoApellido");
					this.OnmamaSegundoApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mamaNombres", DbType="VarChar(50)")]
		public string mamaNombres
		{
			get
			{
				return this._mamaNombres;
			}
			set
			{
				if ((this._mamaNombres != value))
				{
					this.OnmamaNombresChanging(value);
					this.SendPropertyChanging();
					this._mamaNombres = value;
					this.SendPropertyChanged("mamaNombres");
					this.OnmamaNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domDesc", DbType="VarChar(MAX)")]
		public string domDesc
		{
			get
			{
				return this._domDesc;
			}
			set
			{
				if ((this._domDesc != value))
				{
					this.OndomDescChanging(value);
					this.SendPropertyChanging();
					this._domDesc = value;
					this.SendPropertyChanged("domDesc");
					this.OndomDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fIns", DbType="DateTime NOT NULL", IsDbGenerated=true)]
		public System.DateTime fIns
		{
			get
			{
				return this._fIns;
			}
			set
			{
				if ((this._fIns != value))
				{
					this.OnfInsChanging(value);
					this.SendPropertyChanging();
					this._fIns = value;
					this.SendPropertyChanged("fIns");
					this.OnfInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAct", DbType="DateTime")]
		public System.Nullable<System.DateTime> fAct
		{
			get
			{
				return this._fAct;
			}
			set
			{
				if ((this._fAct != value))
				{
					this.OnfActChanging(value);
					this.SendPropertyChanging();
					this._fAct = value;
					this.SendPropertyChanged("fAct");
					this.OnfActChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.caColonias")]
	public partial class caColonias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private string _colonia;
		
		private System.DateTime _fIns;
		
		private System.Nullable<System.DateTime> _fAct;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OncoloniaChanging(string value);
    partial void OncoloniaChanged();
    partial void OnfInsChanging(System.DateTime value);
    partial void OnfInsChanged();
    partial void OnfActChanging(System.Nullable<System.DateTime> value);
    partial void OnfActChanged();
    #endregion
		
		public caColonias()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colonia", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string colonia
		{
			get
			{
				return this._colonia;
			}
			set
			{
				if ((this._colonia != value))
				{
					this.OncoloniaChanging(value);
					this.SendPropertyChanging();
					this._colonia = value;
					this.SendPropertyChanged("colonia");
					this.OncoloniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fIns", DbType="DateTime NOT NULL", IsDbGenerated=true)]
		public System.DateTime fIns
		{
			get
			{
				return this._fIns;
			}
			set
			{
				if ((this._fIns != value))
				{
					this.OnfInsChanging(value);
					this.SendPropertyChanging();
					this._fIns = value;
					this.SendPropertyChanged("fIns");
					this.OnfInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAct", DbType="DateTime")]
		public System.Nullable<System.DateTime> fAct
		{
			get
			{
				return this._fAct;
			}
			set
			{
				if ((this._fAct != value))
				{
					this.OnfActChanging(value);
					this.SendPropertyChanging();
					this._fAct = value;
					this.SendPropertyChanged("fAct");
					this.OnfActChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.caEscuelas")]
	public partial class caEscuelas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _municipio;
		
		private string _institucion;
		
		private string _nivel;
		
		private string _plantel;
		
		private System.DateTime _fIns;
		
		private System.Nullable<System.DateTime> _fAct;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmunicipioChanging(string value);
    partial void OnmunicipioChanged();
    partial void OninstitucionChanging(string value);
    partial void OninstitucionChanged();
    partial void OnnivelChanging(string value);
    partial void OnnivelChanged();
    partial void OnplantelChanging(string value);
    partial void OnplantelChanged();
    partial void OnfInsChanging(System.DateTime value);
    partial void OnfInsChanged();
    partial void OnfActChanging(System.Nullable<System.DateTime> value);
    partial void OnfActChanged();
    #endregion
		
		public caEscuelas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_municipio", DbType="VarChar(50)")]
		public string municipio
		{
			get
			{
				return this._municipio;
			}
			set
			{
				if ((this._municipio != value))
				{
					this.OnmunicipioChanging(value);
					this.SendPropertyChanging();
					this._municipio = value;
					this.SendPropertyChanged("municipio");
					this.OnmunicipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_institucion", DbType="VarChar(60)")]
		public string institucion
		{
			get
			{
				return this._institucion;
			}
			set
			{
				if ((this._institucion != value))
				{
					this.OninstitucionChanging(value);
					this.SendPropertyChanging();
					this._institucion = value;
					this.SendPropertyChanged("institucion");
					this.OninstitucionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nivel", DbType="VarChar(50)")]
		public string nivel
		{
			get
			{
				return this._nivel;
			}
			set
			{
				if ((this._nivel != value))
				{
					this.OnnivelChanging(value);
					this.SendPropertyChanging();
					this._nivel = value;
					this.SendPropertyChanged("nivel");
					this.OnnivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plantel", DbType="VarChar(100)")]
		public string plantel
		{
			get
			{
				return this._plantel;
			}
			set
			{
				if ((this._plantel != value))
				{
					this.OnplantelChanging(value);
					this.SendPropertyChanging();
					this._plantel = value;
					this.SendPropertyChanged("plantel");
					this.OnplantelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fIns", DbType="DateTime NOT NULL")]
		public System.DateTime fIns
		{
			get
			{
				return this._fIns;
			}
			set
			{
				if ((this._fIns != value))
				{
					this.OnfInsChanging(value);
					this.SendPropertyChanging();
					this._fIns = value;
					this.SendPropertyChanged("fIns");
					this.OnfInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAct", DbType="DateTime")]
		public System.Nullable<System.DateTime> fAct
		{
			get
			{
				return this._fAct;
			}
			set
			{
				if ((this._fAct != value))
				{
					this.OnfActChanging(value);
					this.SendPropertyChanging();
					this._fAct = value;
					this.SendPropertyChanged("fAct");
					this.OnfActChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.caLocalidades")]
	public partial class caLocalidades : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private string _localidad;
		
		private System.DateTime _fIns;
		
		private System.Nullable<System.DateTime> _fAct;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnlocalidadChanging(string value);
    partial void OnlocalidadChanged();
    partial void OnfInsChanging(System.DateTime value);
    partial void OnfInsChanged();
    partial void OnfActChanging(System.Nullable<System.DateTime> value);
    partial void OnfActChanged();
    #endregion
		
		public caLocalidades()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_localidad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string localidad
		{
			get
			{
				return this._localidad;
			}
			set
			{
				if ((this._localidad != value))
				{
					this.OnlocalidadChanging(value);
					this.SendPropertyChanging();
					this._localidad = value;
					this.SendPropertyChanged("localidad");
					this.OnlocalidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fIns", DbType="DateTime NOT NULL", IsDbGenerated=true)]
		public System.DateTime fIns
		{
			get
			{
				return this._fIns;
			}
			set
			{
				if ((this._fIns != value))
				{
					this.OnfInsChanging(value);
					this.SendPropertyChanging();
					this._fIns = value;
					this.SendPropertyChanged("fIns");
					this.OnfInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAct", DbType="DateTime")]
		public System.Nullable<System.DateTime> fAct
		{
			get
			{
				return this._fAct;
			}
			set
			{
				if ((this._fAct != value))
				{
					this.OnfActChanging(value);
					this.SendPropertyChanging();
					this._fAct = value;
					this.SendPropertyChanged("fAct");
					this.OnfActChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.caMunicipios")]
	public partial class caMunicipios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private string _municipio;
		
		private System.DateTime _fIns;
		
		private System.Nullable<System.DateTime> _fAct;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnmunicipioChanging(string value);
    partial void OnmunicipioChanged();
    partial void OnfInsChanging(System.DateTime value);
    partial void OnfInsChanged();
    partial void OnfActChanging(System.Nullable<System.DateTime> value);
    partial void OnfActChanged();
    #endregion
		
		public caMunicipios()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_municipio", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string municipio
		{
			get
			{
				return this._municipio;
			}
			set
			{
				if ((this._municipio != value))
				{
					this.OnmunicipioChanging(value);
					this.SendPropertyChanging();
					this._municipio = value;
					this.SendPropertyChanged("municipio");
					this.OnmunicipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fIns", DbType="DateTime NOT NULL", IsDbGenerated=true)]
		public System.DateTime fIns
		{
			get
			{
				return this._fIns;
			}
			set
			{
				if ((this._fIns != value))
				{
					this.OnfInsChanging(value);
					this.SendPropertyChanging();
					this._fIns = value;
					this.SendPropertyChanged("fIns");
					this.OnfInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAct", DbType="DateTime")]
		public System.Nullable<System.DateTime> fAct
		{
			get
			{
				return this._fAct;
			}
			set
			{
				if ((this._fAct != value))
				{
					this.OnfActChanging(value);
					this.SendPropertyChanging();
					this._fAct = value;
					this.SendPropertyChanged("fAct");
					this.OnfActChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.caUsuarios")]
	public partial class caUsuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _cveUsuario;
		
		private string _usuario;
		
		private System.DateTime _fIns;
		
		private System.Nullable<System.DateTime> _fAct;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncveUsuarioChanging(string value);
    partial void OncveUsuarioChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OnfInsChanging(System.DateTime value);
    partial void OnfInsChanged();
    partial void OnfActChanging(System.Nullable<System.DateTime> value);
    partial void OnfActChanged();
    #endregion
		
		public caUsuarios()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cveUsuario", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string cveUsuario
		{
			get
			{
				return this._cveUsuario;
			}
			set
			{
				if ((this._cveUsuario != value))
				{
					this.OncveUsuarioChanging(value);
					this.SendPropertyChanging();
					this._cveUsuario = value;
					this.SendPropertyChanged("cveUsuario");
					this.OncveUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fIns", DbType="DateTime NOT NULL", IsDbGenerated=true)]
		public System.DateTime fIns
		{
			get
			{
				return this._fIns;
			}
			set
			{
				if ((this._fIns != value))
				{
					this.OnfInsChanging(value);
					this.SendPropertyChanging();
					this._fIns = value;
					this.SendPropertyChanged("fIns");
					this.OnfInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAct", DbType="DateTime")]
		public System.Nullable<System.DateTime> fAct
		{
			get
			{
				return this._fAct;
			}
			set
			{
				if ((this._fAct != value))
				{
					this.OnfActChanging(value);
					this.SendPropertyChanging();
					this._fAct = value;
					this.SendPropertyChanged("fAct");
					this.OnfActChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class paListaRegistrosExtendidaResult
	{
		
		private string _curp;
		
		private string _primerApellido;
		
		private string _segundoApellido;
		
		private string _nombres;
		
		private int _idEscuela;
		
		private string _municipio;
		
		private string _institucion;
		
		private string _nivel;
		
		private string _plantel;
		
		private string _domDesc;
		
		private int _edad;
		
		private string _sexo;
		
		private string _correo;
		
		private string _telCel;
		
		private string _telPart;
		
		private System.Nullable<System.Guid> _domIdMpio;
		
		private System.Nullable<System.Guid> _domIdLocalidad;
		
		private System.Nullable<System.Guid> _domIdColonia;
		
		private System.Nullable<System.Guid> _domIdCalle;
		
		private System.Nullable<int> _domNumExt;
		
		private System.Nullable<int> _domNumInt;
		
		private string _domLetra;
		
		private System.DateTime _fIns;
		
		public paListaRegistrosExtendidaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curp", DbType="VarChar(18) NOT NULL", CanBeNull=false)]
		public string curp
		{
			get
			{
				return this._curp;
			}
			set
			{
				if ((this._curp != value))
				{
					this._curp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primerApellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string primerApellido
		{
			get
			{
				return this._primerApellido;
			}
			set
			{
				if ((this._primerApellido != value))
				{
					this._primerApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segundoApellido", DbType="VarChar(50)")]
		public string segundoApellido
		{
			get
			{
				return this._segundoApellido;
			}
			set
			{
				if ((this._segundoApellido != value))
				{
					this._segundoApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this._nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEscuela", DbType="Int NOT NULL")]
		public int idEscuela
		{
			get
			{
				return this._idEscuela;
			}
			set
			{
				if ((this._idEscuela != value))
				{
					this._idEscuela = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_municipio", DbType="VarChar(50)")]
		public string municipio
		{
			get
			{
				return this._municipio;
			}
			set
			{
				if ((this._municipio != value))
				{
					this._municipio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_institucion", DbType="VarChar(60)")]
		public string institucion
		{
			get
			{
				return this._institucion;
			}
			set
			{
				if ((this._institucion != value))
				{
					this._institucion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nivel", DbType="VarChar(50)")]
		public string nivel
		{
			get
			{
				return this._nivel;
			}
			set
			{
				if ((this._nivel != value))
				{
					this._nivel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plantel", DbType="VarChar(100)")]
		public string plantel
		{
			get
			{
				return this._plantel;
			}
			set
			{
				if ((this._plantel != value))
				{
					this._plantel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domDesc", DbType="VarChar(MAX)")]
		public string domDesc
		{
			get
			{
				return this._domDesc;
			}
			set
			{
				if ((this._domDesc != value))
				{
					this._domDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edad", DbType="Int NOT NULL")]
		public int edad
		{
			get
			{
				return this._edad;
			}
			set
			{
				if ((this._edad != value))
				{
					this._edad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this._sexo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(50)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telCel", DbType="VarChar(50)")]
		public string telCel
		{
			get
			{
				return this._telCel;
			}
			set
			{
				if ((this._telCel != value))
				{
					this._telCel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telPart", DbType="VarChar(50)")]
		public string telPart
		{
			get
			{
				return this._telPart;
			}
			set
			{
				if ((this._telPart != value))
				{
					this._telPart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domIdMpio", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> domIdMpio
		{
			get
			{
				return this._domIdMpio;
			}
			set
			{
				if ((this._domIdMpio != value))
				{
					this._domIdMpio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domIdLocalidad", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> domIdLocalidad
		{
			get
			{
				return this._domIdLocalidad;
			}
			set
			{
				if ((this._domIdLocalidad != value))
				{
					this._domIdLocalidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domIdColonia", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> domIdColonia
		{
			get
			{
				return this._domIdColonia;
			}
			set
			{
				if ((this._domIdColonia != value))
				{
					this._domIdColonia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domIdCalle", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> domIdCalle
		{
			get
			{
				return this._domIdCalle;
			}
			set
			{
				if ((this._domIdCalle != value))
				{
					this._domIdCalle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domNumExt", DbType="Int")]
		public System.Nullable<int> domNumExt
		{
			get
			{
				return this._domNumExt;
			}
			set
			{
				if ((this._domNumExt != value))
				{
					this._domNumExt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domNumInt", DbType="Int")]
		public System.Nullable<int> domNumInt
		{
			get
			{
				return this._domNumInt;
			}
			set
			{
				if ((this._domNumInt != value))
				{
					this._domNumInt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domLetra", DbType="NVarChar(2)")]
		public string domLetra
		{
			get
			{
				return this._domLetra;
			}
			set
			{
				if ((this._domLetra != value))
				{
					this._domLetra = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fIns", DbType="DateTime NOT NULL")]
		public System.DateTime fIns
		{
			get
			{
				return this._fIns;
			}
			set
			{
				if ((this._fIns != value))
				{
					this._fIns = value;
				}
			}
		}
	}
	
	public partial class paListaRegistrosReducidaResult
	{
		
		private string _curp;
		
		private string _primerApellido;
		
		private string _segundoApellido;
		
		private string _nombres;
		
		private int _idEscuela;
		
		private System.DateTime _fIns;
		
		private string _municipio;
		
		private string _institucion;
		
		private string _nivel;
		
		private string _plantel;
		
		public paListaRegistrosReducidaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curp", DbType="VarChar(18) NOT NULL", CanBeNull=false)]
		public string curp
		{
			get
			{
				return this._curp;
			}
			set
			{
				if ((this._curp != value))
				{
					this._curp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primerApellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string primerApellido
		{
			get
			{
				return this._primerApellido;
			}
			set
			{
				if ((this._primerApellido != value))
				{
					this._primerApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segundoApellido", DbType="VarChar(50)")]
		public string segundoApellido
		{
			get
			{
				return this._segundoApellido;
			}
			set
			{
				if ((this._segundoApellido != value))
				{
					this._segundoApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this._nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEscuela", DbType="Int NOT NULL")]
		public int idEscuela
		{
			get
			{
				return this._idEscuela;
			}
			set
			{
				if ((this._idEscuela != value))
				{
					this._idEscuela = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fIns", DbType="DateTime NOT NULL")]
		public System.DateTime fIns
		{
			get
			{
				return this._fIns;
			}
			set
			{
				if ((this._fIns != value))
				{
					this._fIns = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_municipio", DbType="VarChar(50)")]
		public string municipio
		{
			get
			{
				return this._municipio;
			}
			set
			{
				if ((this._municipio != value))
				{
					this._municipio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_institucion", DbType="VarChar(60)")]
		public string institucion
		{
			get
			{
				return this._institucion;
			}
			set
			{
				if ((this._institucion != value))
				{
					this._institucion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nivel", DbType="VarChar(50)")]
		public string nivel
		{
			get
			{
				return this._nivel;
			}
			set
			{
				if ((this._nivel != value))
				{
					this._nivel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plantel", DbType="VarChar(100)")]
		public string plantel
		{
			get
			{
				return this._plantel;
			}
			set
			{
				if ((this._plantel != value))
				{
					this._plantel = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
